# ZTP configuration
menu "Configuration"
    depends on PACKAGE_ztp

config ZTP_URL
    depends PACKAGE_ztp
    string "ZTP URL"
    default 0.0.0.0

config ZTP_SECRET
    depends PACKAGE_ztp
    string "ZTP Secret"
    default jBqenDkRHd4ztdTeVeG2hYkM
endmenu